name: Java CI with Maven and SonarCloud in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      # checkout full history (important for Sonar blame)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Java 17
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
          cache: maven

      # cache sonar + maven
      - name: Cache Maven + Sonar
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-

      
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

    
      - name: Enable SonarCloud goal
        if: ${{ env.SONAR_TOKEN }}
        run: echo "SONARGOAL=sonar:sonar" >> $GITHUB_ENV

     
      - name: Build + Test + Coverage + SonarCloud
        run: >
          xvfb-run -a mvn -B -ntp verify -Pjacoco $SONARGOAL
          -Dsonar.organization=perkashlal
          -Dsonar.projectKey=perkashlal_employee-shift
          -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
